// Code generated by protoc-gen-gobee
// source: pb/sum.proto
// DO NOT EDIT!

/*
Package example is a self-registering gRPC and JSON+Swagger service definition.

It conforms to the github.com/daewood/gobee Service interface.
*/
package example

import (
	"net/http"
	"strings"

	"github.com/daewood/gobee/transport"
	"github.com/daewood/gobee/transport/httpruntime"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
)

// SummatorDesc is a descriptor/registrator for the SummatorServer.
type SummatorDesc struct {
	svc SummatorServer
}

// NewSummatorServiceDesc creates new registrator for the SummatorServer.
func NewSummatorServiceDesc(svc SummatorServer) *SummatorDesc {
	return &SummatorDesc{svc: svc}
}

// RegisterGRPC implements service registrator interface.
func (d *SummatorDesc) RegisterGRPC(s *grpc.Server) {
	RegisterSummatorServer(s, d.svc)
}

// SwaggerDef returns this file's Swagger definition.
func (d *SummatorDesc) SwaggerDef() []byte {
	return _swaggerDef_pb_sum_proto
}

// RegisterHTTP registers this service's HTTP handlers/bindings.
func (d *SummatorDesc) RegisterHTTP(mux transport.Router) {

	// Handlers for Sum

	mux.HandleFunc("/"+pattern_gobee_Summator_Sum_0, func(w http.ResponseWriter, r *http.Request) {
		//TODO only POST is supported atm

		inbound, outbound := httpruntime.MarshalerForRequest(r)
		var req SumRequest
		err := inbound.Unmarshal(r.Body, &req)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "couldn't read request JSON"), nil)
			return
		}
		ret, err := d.svc.Sum(r.Context(), &req)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "returned from handler"), nil)
			return
		}

		w.Header().Set("Content-Type", outbound.ContentType())
		err = outbound.Marshal(w, ret)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "couldn't write response"), nil)
			return
		}
	})

	// Handlers for Wait

	mux.HandleFunc("/"+pattern_gobee_Summator_Wait_0, func(w http.ResponseWriter, r *http.Request) {
		//TODO only POST is supported atm

		inbound, outbound := httpruntime.MarshalerForRequest(r)
		var req WaitRequest
		err := inbound.Unmarshal(r.Body, &req)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "couldn't read request JSON"), nil)
			return
		}
		ret, err := d.svc.Wait(r.Context(), &req)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "returned from handler"), nil)
			return
		}

		w.Header().Set("Content-Type", outbound.ContentType())
		err = outbound.Marshal(w, ret)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "couldn't write response"), nil)
			return
		}
	})

	// Handlers for Hello

	mux.HandleFunc("/"+pattern_gobee_Summator_Hello_0, func(w http.ResponseWriter, r *http.Request) {
		//TODO only POST is supported atm

		inbound, outbound := httpruntime.MarshalerForRequest(r)
		var req StrMessage
		err := inbound.Unmarshal(r.Body, &req)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "couldn't read request JSON"), nil)
			return
		}
		ret, err := d.svc.Hello(r.Context(), &req)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "returned from handler"), nil)
			return
		}

		w.Header().Set("Content-Type", outbound.ContentType())
		err = outbound.Marshal(w, ret)
		if err != nil {
			httpruntime.SetError(r.Context(), r, w, errors.Wrap(err, "couldn't write response"), nil)
			return
		}
	})

}

var _swaggerDef_pb_sum_proto = []byte(`{
  "swagger": "2.0",
  "info": {
    "title": "pb/sum.proto",
    "version": "version not set"
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/example/hello": {
      "post": {
        "operationId": "Hello",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/exampleStrMessage"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/exampleStrMessage"
            }
          }
        ],
        "tags": [
          "Summator"
        ]
      }
    },
    "/v1/example/sum": {
      "post": {
        "operationId": "Sum",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/exampleSumResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/exampleSumRequest"
            }
          }
        ],
        "tags": [
          "Summator"
        ]
      }
    },
    "/v1/example/wait": {
      "post": {
        "operationId": "Wait",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/exampleWaitResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/exampleWaitRequest"
            }
          }
        ],
        "tags": [
          "Summator"
        ]
      }
    }
  },
  "definitions": {
    "exampleStrMessage": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      }
    },
    "exampleSumRequest": {
      "type": "object",
      "properties": {
        "a": {
          "type": "string",
          "format": "int64",
          "description": "A is the number we're adding to. Can't be zero for the sake of example."
        },
        "b": {
          "type": "string",
          "format": "int64",
          "description": "B is the number we're adding."
        }
      },
      "description": "SumRequest is a request for Summator service."
    },
    "exampleSumResponse": {
      "type": "object",
      "properties": {
        "sum": {
          "type": "string",
          "format": "int64"
        },
        "error": {
          "type": "string"
        }
      }
    },
    "exampleWaitRequest": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "title": "WaitRequest is only for test"
    },
    "exampleWaitResponse": {
      "type": "object",
      "properties": {
        "error": {
          "type": "string"
        }
      }
    }
  }
}

`)

var (
	pattern_gobee_Summator_Sum_0 = strings.Join([]string{"v1", "example", "sum"}, "/")

	pattern_gobee_Summator_Wait_0 = strings.Join([]string{"v1", "example", "wait"}, "/")

	pattern_gobee_Summator_Hello_0 = strings.Join([]string{"v1", "example", "hello"}, "/")
)
